# Generated by Django 5.2 on 2025-04-30 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('costumers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contracts'),
        ),
    ]
