# Generated by Django 5.2 on 2025-04-30 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0002_customers_contract'),
        ('leads', '0002_leads_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.leads'),
        ),
    ]
