# Generated by Django 5.2 on 2025-04-30 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('costumers', '0003_alter_customers_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contracts'),
        ),
    ]
