# Generated by Django 5.2 on 2025-04-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='budjet',
            new_name='budget',
        ),
    ]
