# Generated by Django 5.2 on 2025-04-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_budjet_ads_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
