# Generated by Django 5.2 on 2025-04-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ads_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='costumers_count',
            new_name='customers_count',
        ),
    ]
