# Generated by Django 5.2 on 2025-04-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('phone', models.CharField(default='+79620620702', max_length=15)),
                ('email', models.EmailField(default='example@mail.ru', max_length=254)),
            ],
        ),
    ]
