# Generated by Django 5.2 on 2025-04-30 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ads_profit'),
        ('leads', '0003_alter_leads_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='ads.ads'),
        ),
    ]
