# Generated by Django 5.2 on 2025-04-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_title_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='cost',
        ),
    ]
